export const data = {
  runningShift:{
    employees : [
      {
        stationID: "01",
        workerName: "Rahul011",
        activeTime: "45:54",
        awayTime: "06:30",
        idealTime: "10:30",
        kiloPicksProduced: "200",
        totalPoints:50,
        otherStatistic: '?',
      },
      {
        stationID: "01",
        workerName: "Rahul011",
        activeTime: "45:54",
        awayTime: "06:30",
        idealTime: "10:30",
        kiloPicksProduced: "200",
        totalPoints:50,
        otherStatistic: '?',
      },
      {
        stationID: "01",
        workerName: "Rahul011",
        activeTime: "45:54",
        awayTime: "06:30",
        idealTime: "10:30",
        kiloPicksProduced: "200",
        totalPoints:50,
        otherStatistic: '?',
      },
      {
        stationID: "01",
        workerName: "Rahul011",
        activeTime: "45:54",
        awayTime: "06:30",
        idealTime: "10:30",
        kiloPicksProduced: "200",
        totalPoints:50,
        otherStatistic: '?',
      },
      {
        stationID: "01",
        workerName: "Rahul011",
        activeTime: "45:54",
        awayTime: "06:30",
        idealTime: "10:30",
        kiloPicksProduced: "200",
        totalPoints:50,
        otherStatistic: '?',
      },
      {
        stationID: "01",
        workerName: "Rahul011",
        activeTime: "45:54",
        awayTime: "06:30",
        idealTime: "10:30",
        kiloPicksProduced: "200",
        totalPoints:50,
        otherStatistic: '?',
      },
      {
        stationID: "01",
        workerName: "Rahul011",
        activeTime: "45:54",
        awayTime: "06:30",
        idealTime: "10:30",
        kiloPicksProduced: "200",
        totalPoints:50,
        otherStatistic: '?',
      },
      {
        stationID: "01",
        workerName: "Rahul011",
        activeTime: "45:54",
        awayTime: "06:30",
        idealTime: "10:30",
        kiloPicksProduced: "200",
        totalPoints:50,
        otherStatistic: '?',
      },{
        stationID: "01",
        workerName: "Rahul011",
        activeTime: "45:54",
        awayTime: "06:30",
        idealTime: "10:30",
        kiloPicksProduced: "200",
        totalPoints:50,
        otherStatistic: '?',
      },
      {
        stationID: "01",
        workerName: "Rahul011",
        activeTime: "45:54",
        awayTime: "06:30",
        idealTime: "10:30",
        kiloPicksProduced: "200",
        totalPoints:50,
        otherStatistic: '?',
      },
      {
        stationID: "01",
        workerName: "Rahul011",
        activeTime: "45:54",
        awayTime: "06:30",
        idealTime: "10:30",
        kiloPicksProduced: "200",
        totalPoints:50,
        otherStatistic: '?',
      },
      {
        stationID: "01",
        workerName: "Rahul011",
        activeTime: "45:54",
        awayTime: "06:30",
        idealTime: "10:30",
        kiloPicksProduced: "200",
        totalPoints:50,
        otherStatistic: '?',
      },{
        stationID: "01",
        workerName: "Rahul011",
        activeTime: "45:54",
        awayTime: "06:30",
        idealTime: "10:30",
        kiloPicksProduced: "200",
        totalPoints:50,
        otherStatistic: '?',
      },
      {
        stationID: "01",
        workerName: "Rahul011",
        activeTime: "45:54",
        awayTime: "06:30",
        idealTime: "10:30",
        kiloPicksProduced: "200",
        totalPoints:50,
        otherStatistic: '?',
      },
      {
        stationID: "01",
        workerName: "Rahul011",
        activeTime: "45:54",
        awayTime: "06:30",
        idealTime: "10:30",
        kiloPicksProduced: "200",
        totalPoints:50,
        otherStatistic: '?',
      },
      {
        stationID: "01",
        workerName: "Rahul011",
        activeTime: "45:54",
        awayTime: "06:30",
        idealTime: "10:30",
        kiloPicksProduced: "200",
        totalPoints:50,
        otherStatistic: '?',
      },
    ]
  }
};

